#!/bin/bash -l
#PBS -N sCO2_03
#PBS -l nodes=1:ppn=20
#PBS -l walltime=24:00:00
#PBS -A asr20_collab

#Setup openfoam
source /storage/work/asr20/OpenFOAM/SetupOpenFOAM-Personal.sh

#Set some consts
N_PROCS=20
PROB_DIR=sCO2Channel-DES_03
SOLVER=buoyantPimpleFoam

#Set up the job
cd $HOME/scratch/$PROB_DIR

#Initial run
mpirun -np $N_PROCS $SOLVER -parallel > log.txt

