#!/bin/bash -l
#PBS -N F300H3
#PBS -l nodes=8:ppn=20
#PBS -l walltime=40:00:00
#PBS -A asr20_b_g_sc_default


#Set up the job
cd $PBS_O_WORKDIR


module load gcc
module use /gpfs/group/asr20/default/sw/modules
module load openmpi/test1

export PERSONAL_INSTALL="TRUE"
source /storage/work/asr20/OpenFOAM/OpenFOAM-v1612+/etc/bashrc

export WM_PROJECT_USER_DIR=$HOME/$WM_PROJECT/$USER-$WM_PROJECT_VERSION
export FOAM_USER_APPBIN=$WM_PROJECT_USER_DIR/platforms/$WM_OPTIONS/bin
export FOAM_USER_LIBBIN=$WM_PROJECT_USER_DIR/platforms/$WM_OPTIONS/lib
export PATH=$PATH:$FOAM_USER_APPBIN
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FOAM_USER_LIBBIN

# Run
mpirun -np 160 chtMultiRegionFoam_GAdaptDoubleCyc -parallel > log.txt

# Reconstruct
# reconstructPar -latestTime -allRegions
