#!/bin/bash -l
#PBS -N sCO2_Val2_DES
#PBS -l nodes=4:ppn=10
#PBS -l walltime=240:00:00
#PBS -A asr20_a_g_sc_default

#Setup openfoam
source /storage/home/mmn5264/OpenFOAM/SetupOpenFOAM-Personal.sh

#Set some consts
N_PROCS=40
PROB_DIR=sCO2Channel-DES_1.03_500_20
SOLVER=buoyantPimpleFoam

#Set up the job
cd $HOME/scratch/$PROB_DIR

#Initial run
mpirun -np $N_PROCS $SOLVER -parallel > $PROB_DIR.txt

