#!/bin/bash -l
#PBS -N sCO2-12-DES_LibTest
#PBS -l nodes=5:ppn=20
#PBS -l walltime=24000:00:00
#PBS -A asr20_collab

#Setup openfoam
source /storage/work/asr20/OpenFOAM/SetupOpenFOAM.sh

#Set some consts
N_PROCS=100
PROB_DIR=sCO2Channel-DES_LibTest
SOLVER=buoyantPimpleFoam

#Set up the job
cd $HOME/scratch/$PROB_DIR

#Initial run
mpirun -np $N_PROCS $SOLVER -parallel > $PROB_DIR.txt

logsize_old=`du -b $PROB_DIR.txt`

while [ ! -a DONE ] ; do
	sleep 10m
	logsize=`du -b $PROB_DIR.txt`
	if [ "$logsize" == "$logsize_old" ] ; then
		echo "Your Job is Frozen..."
		killall $SOLVER
		mpirun -np $N_PROCS $SOLVER -parallel > $PROB_DIR.txt && touch DONE &
	fi
logsize_old=$logsize
done

